### PR TITLE
Code Challenge - I apologize for my linear thinking! I value simplicity & Readability above all!

### PR DESCRIPTION
**Pull request by TarunApp**
I created 2 other files 'New-York-Knicks.json` and `Roman-Cities.json`, these were scraped using HTTP requests, but for the `van-gogh-paintings.json` I loaded in the file directly for parsing. Tech used: Python, BeautifulSoup, Selenium, JSON Library.

### CODE REVIEW

**Comment by TarunApp** [comment]
I'm going to work on the Ruby version and create a PR for it after I learn up on the language!

**Review by ilyazub — CHANGES_REQUESTED** [review]
@TarunApp Thanks for solving the code challenge!

Please add tests for the solution.

**Review by TarunApp — COMMENTED** [review]
Accept Changes.

**Comment by TarunApp** [comment]
@ilyazub Sorry for the late reply. I tested the solution by scraping the terms 'New York Knicks Roster' and 'Roman Cities' on Google. I scraped those and put them in the repository along with the script and the original Van-Gogh Paintings result JSON file. Please let me know if these are adequate for tests. 

I also want to use the Python submission. The Ruby one is just for me to apply what I learn, it might take a bit longer, Ruby has a lot of interesting features that I'm still trying to understand!

**Review by ilyazub — COMMENTED** [review]
> @ilyazub Sorry for the late reply. I tested the solution by scraping the terms 'New York Knicks Roster' and 'Roman Cities' on Google. I recently added 2 files which are testing the search terms that bring up the carosuels - 'Famous Boxers' and 'Famous Basketball Players'.
> 
> I scraped those and put them in the repository along with the script and the original Van-Gogh Paintings result JSON file. Please let me know if these are adequate for tests and if I conducted the test in the manner you wanted.
> 
> I also want to use the Python submission. The Ruby one is just for me to apply what I learn, it might take a bit longer, Ruby has a lot of interesting features that I'm still trying to understand! Like the Poignant Guide, its really like making sentences with code!

@TarunApp Makes sense :+1: I didn't know you've applied to the Customer Success position during my initial review.

By adding tests I've meant [unit tests](https://docs.python.org/3/library/unittest.html) but it's not required for Customer Success specialists.

**Pull request closed without merging**
