### PR TITLE
Gildas solution

### PR DESCRIPTION
**Pull request by gildas-lormeau**
Here is my implementation in JavaScript. See the README.MD file for more information.

### CODE REVIEW

**Comment by aciddjus** [comment]
Hi Gildas. As you pointed out, images are either partially or not at all extracted from the page.

Screenshot 2022-03-14 131645

Do you want to give it another shot in extracting full images from javascript?

**Comment by gildas-lormeau** [comment]
I added the missing code in order to enable JavaScript in jsdom, emulate a large screen, and consequently get the URLs of lazy-loaded images.

**Comment by gildas-lormeau** [comment]
Sorry for the additional changes, I think the code is ready for the review now.

**Comment by gildas-lormeau** [comment]
Sorry, I couldn't help but make a few minor changes while reviewing the code myself!

**Comment by aciddjus** [comment]
> Sorry, I couldn't help but make a few minor changes while reviewing the code myself!

That's ok. I'll review it tomorrow, so no worries if you need to make more changes.

**Comment by gildas-lormeau** [comment]
For anyone reading this PR, know that this is a bad solution. It's bad because it's not coded in Ruby, and it uses jsdom to run Google scripts. The right solution is to use regular expressions because it is better and you can't argue with that.

**Pull request closed without merging**
