### PR TITLE
Update Vincent van Gogh paintings example

### PR DESCRIPTION
**Pull request by andypple83**
This PR is to update the Van Gogh paintings example.

### Tasks
- [x] Update the latest HTML file
- [x] Update the latest JSON results from SerpApi
- [x] Update the latest expected array JSON

van-gogh-paintings

### CODE REVIEW

**Review by zyc9012 — CHANGES_REQUESTED** [review]
Thanks @andypple83 👍. 

Let's use the unmodified version of the HTML that SerpApi parses.

**Review by zyc9012 — CHANGES_REQUESTED** [review]
Thanks @andypple83. Let's update `files/van-gogh-paintings.json` and `files/expected-array.json` due to HTML change.

**Comment by andypple83** [comment]
Thanks @zyc9012 . I picked the wrong branch and diff files. I've updated all the files. Please help me to review again. 👍

**Review by zyc9012 — APPROVED** [review]
Thanks @andypple83 👍 

The png can be compressed a lot using https://tinypng.com/.

**Comment by andypple83** [comment]
Thanks @zyc9012. I think the size is still acceptable in this case. I'll keep this in mind for the next update. 👍

**Pull request merged**
