### PR TITLE
The parser implementation

### PR DESCRIPTION
**Pull request by Neodelf**
Notes:
1. Namespaces support the maintenance of the Parser system. It helps to add new sources of HTML.
2. Input and Output classes are used for comfortable usage of Workers. They are used for extension input sources and output formats.
3. The worker's versioning allows the adoption of workers for new HTML sources if the source changes.
4. Added `dali` and `picasso` painting sources as the last updated examples to show the convenient extensibility of the system. They are used by V2::Worker.

The solution is designed as a starting point for further development of the system as a gem.

### CODE REVIEW

**Comment by andypple83** [comment]
With this multiple versions design, how do we support both HTML layouts on production?

**Comment by Neodelf** [comment]
Hey @andypple83, good catch!

I needed to add two new layouts for testing based on the task specs. Noticed Google's layout changed
van-gogh-paintings-2023-10-25
from what we had in the repository van-gogh-paintings
That's why I created `Parser::Artworks::Google::V2::Worker`.

As for supporting multiple HTML layouts in the prod — no need. We're tailoring our parser to the current Google output. I implemented worker versioning to handle any HTML changes.

What do you think?

**Comment by andypple83** [comment]
We supported both versions, Google sometimes returns different layouts for different keywords. If we want to support both versions, how can you design your solution?

**Comment by Neodelf** [comment]
@andypple83,

If we don't know what version of the layout we have, we could run different `workers` in parallel and compare results. One of them will return the correct answer. If there is no correct result, here is a new layout, and we need to create a new worker for it. I believe the situation will not raise frequently, but a fast reaction will save money and customer loyalty.

The solution is scalable for parsing other sections like `questions`.

**Comment by Neodelf** [comment]
I would like to add a note about scalability.

If we add the parser for different sections as I mentioned above for `questions`, we could join workers for a `carousel` in one job, and workers for `questions` in another.
Inside the job, we could use a prioritized queue and place workers according to frequent usage in parsing.

**Comment by Neodelf** [comment]
Hi @andypple83!

> With this multiple versions design, how do we support both HTML layouts on production?

I would suggest another approach to implement it.

The idea is to build a pipeline. The pipeline is a prioritized queue. Each element in the queue is a worker. Each worker tries to parse the Google results. If one fails, the pipeline starts using the next worker. If the pipeline returns nil, it means that we need to save the results and write another worker for it.

If there is an option to continue the discussion, I would like to code it.
Please let me know if you want to continue.

**Pull request closed without merging**
